language: php
php:
- 5.2
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
env:
- DB=mysql
matrix:
  exclude:
  - php: hhvm
  allow_failures:
  - php: hhvm
before_script:
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;"
  -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-text
notifications:
  irc: irc.freenode.org#yourfavouriteroomfortravis
deploy:
  provider: heroku
  api_key:
    secure: NqR/QLmbbBHXmn7/akkeSktpFUfNlg7Cz2w/a7AEmxpwBTehU7j1TCCzys16oONN4AypOxfVbgIldGIFHLG4AqUlOXRIQdmcLU21TREH3dAGFuTF9ZgN709rJQkQZv2gEoS+VMIwetnNX7UzKZE3diXU3U2PkuSF56xzjMjRhbMqbC5PO6I63A9tXnPEtBmA+DCBBJUPpPVM1xIl7C022Y54EueYlgWin0oLJzigktUcHDvjEqN02DOEXVWUmFLo7G5qtlqt0w5287nt6i40Fk6WYE/qKW0M4bgoSI7dgtqCtn5To42NPgF7DF2Tb2G7ww/cMXwUaPqQmL/pY8mKCmhALuI/3ABSiC7xwFd0j+/qNHnC98IsCqFhHS57YoHOKv8pLPbcYdDcYQVzKgEEDrjuOrJMwWnnOkOWY3idh1LZQCsei6jUah3g/I/BEPMpfYd2jUv78kKM7UFNu94r6gEe3tJGowjoMpAXTkXJRi+JCB7m3UF0AYhYDdORBpqWg5m4zoD5MgdYFnc5HUoDUTtBMpQhyt6Mtib7pF32/vXPlOnGyF1fcbQnTpQK5ey5/FsvzN7j1RU6mM3lFiWF+MK/6FGr7OvElJlhenHax54c/2m5lXB7RUZnhJI0HwgMSxVFGBgq7nWZ0n1lr2Exa1dutwI2gtdhL5pIeYviTmk=
  app: travis-heroku-demo
  on:
    repo: adityamaddala/travis-heroku-demo
